package com.pradheep.dao.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated Jun 14, 2017 11:13:22 AM by Hibernate Tools 5.2.1.Final

/**
 * ContactUs generated by hbm2java
 */

@Entity
@Table(name = "bible_verse")
public class BibleVerse implements java.io.Serializable {

	@Id
	@Column(name = "id")
	@GeneratedValue
	public Integer Id;

	@Column(name = "verse")
	public String verse;
	
	@Column(name = "chapter")
	public String chapter;
	
	@Column(name = "eng_verse")
	public String engVerse;
	
	@Column(name = "eng_chapter")
	public String engChapter;

	public Integer getId() {
		return Id;
	}

	public void setId(Integer id) {
		Id = id;
	}

	public String getVerse() {
		return verse;
	}

	public void setVerse(String verse) {
		this.verse = verse;
	}

	public String getChapter() {
		return chapter;
	}

	public void setChapter(String chapter) {
		this.chapter = chapter;
	}

	public String getEngVerse() {
		return engVerse;
	}

	public void setEngVerse(String engVerse) {
		this.engVerse = engVerse;
	}

	public String getEngChapter() {
		return engChapter;
	}

	public void setEngChapter(String engChapter) {
		this.engChapter = engChapter;
	}	
	

}
