package com.pradheep.dao.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated Jun 14, 2017 11:13:22 AM by Hibernate Tools 5.2.1.Final

/**
 * ContactUs generated by hbm2java
 */

@Entity
@Table(name = "contact_us")
public class ContactUs implements java.io.Serializable {

	@Id
	@Column(name = "contact_id")
	@GeneratedValue
	public Integer contactId;

	@Column(name = "name")
	public String name;
	
	@Column(name = "information")
	public String information;
	
	@Column(name = "contact_email")
	public String contactEmail;
	
	@Column(name = "contact_number")
	public String contactNumber;

	public Integer getContactId() {
		return contactId;
	}

	public void setContactId(Integer contactId) {
		this.contactId = contactId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getInformation() {
		return information;
	}

	public void setInformation(String information) {
		this.information = information;
	}

	public String getContactEmail() {
		return contactEmail;
	}

	public void setContactEmail(String contactEmail) {
		this.contactEmail = contactEmail;
	}

	public String getContactNumber() {
		return contactNumber;
	}

	public void setContactNumber(String contactNumber) {
		this.contactNumber = contactNumber;
	}

}
