package com.pradheep.dao.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated Jun 14, 2017 11:13:22 AM by Hibernate Tools 5.2.1.Final

/**
 * ContactUs generated by hbm2java
 */

@Entity
@Table(name = "daily_verse_entry")
public class DailyVerseEntry implements java.io.Serializable {

	@Id
	@Column(name = "id")
	@GeneratedValue
	public Integer Id;

	@Column(name = "date")
	public String date;
	
	@Column(name = "verse_id")
	public int bibleVerseRef;

	public Integer getId() {
		return Id;
	}

	public void setId(Integer id) {
		Id = id;
	}

	public String getDate() {
		return date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public int getBibleVerseRef() {
		return bibleVerseRef;
	}

	public void setBibleVerseRef(int bibleVerseRef) {
		this.bibleVerseRef = bibleVerseRef;
	}

}
