package com.pradheep.dao.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated Jun 14, 2017 11:13:22 AM by Hibernate Tools 5.2.1.Final

/**
 * ContactUs generated by hbm2java
 */

@Entity
@Table(name = "prayers")
public class PrayersModel implements java.io.Serializable {

	@Id
	@Column(name = "id")
	@GeneratedValue
	public Integer id;

	@Column(name = "prayers_title_en")
	public String titleEnglish;

	@Column(name = "prayers_title_ta")
	public byte[] titleTamil;

	@Column(name = "prayer_en")
	public String prayerEnglish;

	@Column(name = "prayer_ta")
	public byte[] prayerTamil;

	@Column(name = "reference_en")
	public String referenceEnglish;

	@Column(name = "reference_ta")
	public byte[] referenceTamil;	
	
	@Column(name="last_changed_by")
	public String lastChangedBy;
	
	@Column(name="last_changed_date")
	public Date lastChangedDate;
	
	@Column(name="is_approved")
	public boolean isApproved;
	
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitleEnglish() {
		return titleEnglish;
	}

	public void setTitleEnglish(String titleEnglish) {
		this.titleEnglish = titleEnglish;
	}

	public byte[] getTitleTamil() {
		return titleTamil;
	}

	public void setTitleTamil(byte[] titleTamil) {
		this.titleTamil = titleTamil;
	}

	public String getPrayerEnglish() {
		return prayerEnglish;
	}

	public void setPrayerEnglish(String prayerEnglish) {
		this.prayerEnglish = prayerEnglish;
	}

	public byte[] getPrayerTamil() {
		return prayerTamil;
	}

	public void setPrayerTamil(byte[] prayerTamil) {
		this.prayerTamil = prayerTamil;
	}

	public String getReferenceEnglish() {
		return referenceEnglish;
	}

	public void setReferenceEnglish(String referenceEnglish) {
		this.referenceEnglish = referenceEnglish;
	}

	public byte[] getReferenceTamil() {
		return referenceTamil;
	}

	public void setReferenceTamil(byte[] referenceTamil) {
		this.referenceTamil = referenceTamil;
	}
}
