package com.pradheep.dao.model;
// Generated Jun 14, 2017 11:13:22 AM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VisitCounter generated by hbm2java
 */
@Entity
@Table(name = "visit_counter")
public class VisitCounter implements java.io.Serializable {

	@Id
	@Column(name = "id")
	@GeneratedValue
	private Integer id;
	
	@Column(name = "page_ref")
	public String pageRef;
	
	@Column(name = "counter")
	public String counter;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getPageRef() {
		return pageRef;
	}

	public void setPageRef(String pageRef) {
		this.pageRef = pageRef;
	}

	public String getCounter() {
		return counter;
	}

	public void setCounter(String counter) {
		this.counter = counter;
	}

	public String toString(){
		return getPageRef();
	}

}
